### ISSUE TITLE
0.6 Android - Java.Lang.NoClassDefFoundError: Didn't find class "com.getkeepsafe.relinker.ReLinker"

### ISSUE THREAD

**Issue by distantcam** [twilio/TwilioChatXamarinBindings#33]
I work for a company that's making a Xamarin Forms app, and we are using the Twilio Chat service in our app.

After upgrading to 0.6 to try and fix another issue, we are now seeing a number of issues with the same exception from our Android customers.

`Java.Lang.NoClassDefFoundError: Didn't find class "com.getkeepsafe.relinker.ReLinker"`

Here's the details from one of the reports in App Center.

```
"exception": {
    "type": "Java.Lang.NoClassDefFoundError",
    "message": "Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;",
    "stackTrace": "  at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <9d32f6b4e6664ba28d2801db94a00b54>:0 \n  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <9d32f6b4e6664ba28d2801db94a00b54>:0 \n  at Com.Twilio.Chat.ChatClient.Create (Android.Content.Context context, System.String token, Com.Twilio.Chat.ChatClient+ClientProperties properties, Com.Twilio.Chat.CallbackListener`1[T] listener) [0x00095] in <629474235f234079a0c1e4993f5984da>:0 \n  at MobilityClient.Droid.TwilioChat.TwilioChatService.Initialise (System.String token) [0x0008e] in <38260fe8cbff440abd9da8893cbaae7f>:0 \n  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---\njava.lang.NoClassDefFoundError: Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;\n\tat com.twilio.chat.ChatClient.loadNativeLibraries(ChatClient.java:183)\n\tat com.twilio.chat.ChatClient.<init>(ChatClient.java:373)\n\tat com.twilio.chat.ChatClient.create(ChatClient.java:284)\n\tat mono.java.lang.RunnableImplementor.n_run(Native Method)\n\tat mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)\n\tat android.os.Handler.handleCallback(Handler.java:789)\n\tat android.os.Handler.dispatchMessage(Handler.java:98)\n\tat androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)\n\tat androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)\n\tat androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)\n\tat androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:102)\n\tat androidx.test.espresso.action.Tap$1.a(Tap.java:5)\n\tat androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)\n\tat androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)\n\tat androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)\n\tat androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.os.Handler.handleCallback(Handler.java:789)\n\tat android.os.Handler.dispatchMessage(Handler.java:98)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6938)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)\nCaused by: java.lang.ClassNotFoundException: Didn't find class \"com.getkeepsafe.relinker.ReLinker\" on path: DexPathList[[zip file \"/system/framework/android.test.runner.jar\", zip file \"/data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/base.apk\", zip file \"/data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/base.apk\"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/lib/arm64, /data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/lib/arm64, /data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/base.apk!/lib/arm64-v8a, /data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]\n\tat dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:379)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:312)\n\t... 24 more\n",
    "innerExceptions": [
      {
        "type": "Java.Lang.ClassNotFoundException",
        "message": "Didn't find class \"com.getkeepsafe.relinker.ReLinker\" on path: DexPathList[[zip file \"/system/framework/android.test.runner.jar\", zip file \"/data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/base.apk\", zip file \"/data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/base.apk\"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/lib/arm64, /data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/lib/arm64, /data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/base.apk!/lib/arm64-v8a, /data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]",
        "stackTrace": "\n  --- End of managed Java.Lang.ClassNotFoundException stack trace ---\njava.lang.ClassNotFoundException: Didn't find class \"com.getkeepsafe.relinker.ReLinker\" on path: DexPathList[[zip file \"/system/framework/android.test.runner.jar\", zip file \"/data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/base.apk\", zip file \"/data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/base.apk\"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/lib/arm64, /data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/lib/arm64, /data/app/androidx.test.tools.crawler-owuaPSHy_8k0yckUIw8wIw==/base.apk!/lib/arm64-v8a, /data/app/au.org.mobility.app-QIzetkRKYRupOC6hxCou5w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]\n\tat dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:379)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:312)\n\tat com.twilio.chat.ChatClient.loadNativeLibraries(ChatClient.java:183)\n\tat com.twilio.chat.ChatClient.<init>(ChatClient.java:373)\n\tat com.twilio.chat.ChatClient.create(ChatClient.java:284)\n\tat mono.java.lang.RunnableImplementor.n_run(Native Method)\n\tat mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)\n\tat android.os.Handler.handleCallback(Handler.java:789)\n\tat android.os.Handler.dispatchMessage(Handler.java:98)\n\tat androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)\n\tat androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)\n\tat androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)\n\tat androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:102)\n\tat androidx.test.espresso.action.Tap$1.a(Tap.java:5)\n\tat androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)\n\tat androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)\n\tat androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)\n\tat androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.os.Handler.handleCallback(Handler.java:789)\n\tat android.os.Handler.dispatchMessage(Handler.java:98)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6938)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)\n",
        "wrapperSdkName": "appcenter.xamarin"
      }
    ],
    "wrapperSdkName": "appcenter.xamarin"
  },
```

**Comment by thisisthekap** [comment]
Looks kind of similar to https://forums.xamarin.com/discussion/124739/problems-using-twilio-programmable-voice-in-a-xamarin-android-bindings-library. So there seems to be an issue with the Xamarin.Android Binding.

@berkus Could this issue have been introduced when fixing #30?

**Comment by distantcam** [comment]
Yep so adding the relinker nuget solved the problem. There's no doco about this. The sample was fixed with this commit that has the relevant change buried in it.

https://github.com/twilio/TwilioChatXamarinBindings/commit/a412c2ab7565fe8fc7200e18a2b37ce3186b949b

**Comment by thisisthekap** [comment]
@distantcam Great! I think this is a workaround we can go with. Anyways, this issue should imho be fixed, or at lease the additional nuget dependency should be carefully documented.

**Comment by berkus** [comment]
Please take a look at the demo app in this very repository - you need to add ReLinker nuget to your _APP_ dependencies. Unfortunately, it doesn't work if we depend the SDK build on it, so it's a necessary step for end-user to perform.

**Comment by berkus** [comment]
I will update the readme about it for the next release (which is imminently pending).

**Comment by distantcam** [comment]
Relinker could be added as a dependency of the nuget package.

https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element

**Comment by berkus** [comment]
@distantcam I'll try that, thanks! Lets see if the next version works better with that.

**Comment by berkus** [comment]
@distantcam @thisisthekap please test 0.7.0!
